runtime: custom
env: flex
service: default

network:
  instance_tag: battleplanner-api

resources:
  cpu: 1
  memory_gb: 0.6

health_check:
  enable_health_check: True
  check_interval_sec: 5
  timeout_sec: 4
  unhealthy_threshold: 2
  healthy_threshold: 2

manual_scaling:
  instances: 1

env_variables:
  NODE_ENV: production
  PUBLIC_ORIGIN: http://battleplanner-162115.appspot.com
  STEAM_REALM: battleplanner-162115.appspot.com
  STEAM_KEY: 758275E6152418D20FFD77BE0317006D
  CLIENT_ORIGIN: http://battleplanner-162115.appspot.com
  REPLAY_BUCKET_NAME: replays-battleplanner
  PROJECT_ID: battleplanner-162115
